# Generated by Django 4.2.7 on 2023-11-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('image_link', models.URLField(blank=True)),
                ('priority', models.PositiveIntegerField(help_text='Enter a number to sort by priority.')),
                ('tag', models.CharField(choices=[('Movie', 'Movie'), ('Show', 'Show'), ('Game', 'Game')], default='Movie', help_text='Select a tag to categorize the media type.', max_length=5)),
            ],
            options={
                'ordering': ['priority', 'title'],
            },
        ),
    ]
